#!/bin/bash

echo "🚀 AICOO - Railway + Vercel Deployment"
echo "======================================"
echo ""
echo "This script will help you deploy AICOO to production."
echo ""

# Check if Railway CLI is installed
if ! command -v railway &> /dev/null; then
    echo "📦 Installing Railway CLI..."
    npm install -g @railway/cli
fi

# Check if Vercel CLI is installed
if ! command -v vercel &> /dev/null; then
    echo "📦 Installing Vercel CLI..."
    npm install -g vercel
fi

echo ""
echo "=================================="
echo "STEP 1: Deploy Backend to Railway"
echo "=================================="
echo ""
echo "Run these commands:"
echo ""
echo "  railway login"
echo "  railway init"
echo "  railway up"
echo ""
echo "After deployment, Railway will give you a URL like:"
echo "  https://aicoo-backend-production.up.railway.app"
echo ""
echo "Then set environment variables in Railway dashboard:"
echo "  - SHOPIFY_API_KEY"
echo "  - SHOPIFY_API_SECRET"
echo "  - OPENAI_API_KEY"
echo "  - FEDEX_CLIENT_ID (optional)"
echo "  - UPS_CLIENT_ID (optional)"
echo "  - DHL_API_KEY (optional)"
echo "  - PORT=3000"
echo "  - NODE_ENV=production"
echo ""
read -p "Press Enter when backend is deployed and variables are set..."

echo ""
echo "=================================="
echo "STEP 2: Deploy Frontend to Vercel"
echo "=================================="
echo ""
echo "Run these commands:"
echo ""
echo "  cd frontend"
echo "  vercel login"
echo "  vercel --prod"
echo ""
echo "Vercel will give you a URL like:"
echo "  https://aicoo.vercel.app"
echo ""
echo "Set environment variable in Vercel:"
echo "  VITE_API_URL = <your-railway-backend-url>"
echo ""
read -p "Press Enter when frontend is deployed..."

echo ""
echo "=================================="
echo "STEP 3: Shopify App Configuration"
echo "=================================="
echo ""
echo "1. Go to https://partners.shopify.com"
echo "2. Create new app or select existing"
echo "3. Configure URLs:"
echo ""
echo "   App URL: <your-vercel-frontend-url>"
echo "   Allowed redirect: <vercel-url>/auth/callback"
echo ""
echo "4. Set webhook URLs:"
echo ""
echo "   Orders Create: <railway-url>/api/webhooks/shopify/orders"
echo "   Orders Update: <railway-url>/api/webhooks/shopify/orders"
echo ""
echo "5. Required API scopes:"
echo "   - read_orders"
echo "   - write_orders"
echo "   - read_shipping"
echo "   - write_shipping"
echo "   - read_customers"
echo ""
echo "6. Copy API credentials and add to Railway:"
echo "   - SHOPIFY_API_KEY"
echo "   - SHOPIFY_API_SECRET"
echo ""
read -p "Press Enter when Shopify app is configured..."

echo ""
echo "=================================="
echo "STEP 4: Test the Deployment"
echo "=================================="
echo ""
echo "1. Install app on your development store"
echo "2. Create a test order"
echo "3. Check AICOO dashboard for the order"
echo "4. Test carrier rate shopping"
echo ""
echo "Your AICOO URLs:"
echo "  Frontend: <vercel-url>"
echo "  Backend: <railway-url>"
echo "  API Health: <railway-url>/api/health"
echo ""
echo "=================================="
echo "✅ Deployment Complete!"
echo "=================================="
